# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '7170242d-eb74-4b23-9435-3bb57e169d53'
  # Web app name
  webAppName: 'gp-node'
  # Environment name
  environmentName: 'gp-node'
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

# pool:
#   vmImage: 'ubuntu-latest'

# steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '10.x'
#   displayName: 'Install Node.js'

# - script: |
#     npm install
#   displayName: 'npm install'
  
# - task: CmdLine@2
#   inputs:
#     script: 'npm run develop'


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '12.9'
      displayName: 'Install Node.js'
    - script: |
        npm run install
      displayName: 'npm install'
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true
    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop
      
- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy: gp-node'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              runtimeStack: 'NODE|12.9'
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
          - task: CmdLine@2
            displayName: 'Azure Web App Deploy: gp-node'
            inputs:
              script: 'npm run develop'